job:
  name : 'n_best_list'
  chdir: true
  config:
    override_dirname:
      exclude_keys:
        - data
        - weights.*
run:
  dir: ../../hydra_outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
sweep:
  dir: ${hydra.run.dir}/
  subdir: ${hydra.job.num}
sweeper:
  # @package hydra.sweeper
  sampler:
    _target_: optuna.samplers.TPESampler
    seed: 123
    consider_prior: true
    prior_weight: 1.0
    consider_magic_clip: true
    consider_endpoints: false
    n_startup_trials: 10
    n_ei_candidates: 24
    multivariate: false
    warn_independent_sampling: true
  _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
  direction: minimize
  storage: null
  study_name: sphere
  n_trials: 100
  n_jobs: 1
  # max_failure_rate: 0.0
  params:
    weights.first_pass_score: interval(-1.6, -1.5) # range(-2.5, -1.5, 0.5)
    weights.am_score: interval(-1.0,0.0) # 0,-0.1,-0.5,-1
    weights.bpe_lm_score: interval(1.9, 2.0) # range(1.5, 2.5, 0.5)
    weights.first_pass_length_penalty: interval(-2.7, -2.5) # range(-2.5, -1.5, 0.5)
    weights.ngram_lm_score: interval(-2.1, -1.9) # range(-2.5, -1.5, 0.5)
    weights.diffusion_score: interval(0.00,0.0026) # 0.0025 # 0,0.0001,0.001,0.002
