hydra:
  run:
    dir: ../hydra_outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${hydra.run.dir}/
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params:
      weights.first_pass_score: range(-2.5, -1.5, 0.5)
      weights.am_score: 0,-0.5,-1
      weights.bpe_lm_score: range(1.5, 2.5, 0.5)
      weights.first_pass_length_penalty: range(-2.5, -1.5, 0.5)
      weights.ngram_lm_score: range(-2.5, -1.5, 0.5)
      weights.diffusion_score: 0,0.0001,0.001
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra: []
    task:
    - hydra=sweep
    - ++diff_score_list=/exp/exp4/acq22mc/diff_list/logs/nbest_exp/e330_euler10_n10.csv
  job:
    name: n_best_list
    chdir: true
    override_dirname: ++diff_score_list=/exp/exp4/acq22mc/diff_list/logs/nbest_exp/e330_euler10_n10.csv,hydra=sweep
    id: ???
    num: ???
    config_name: rescoring
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys:
        - data
        - weights.*
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /exp/exp4/acq22mc/diff_list/Grad-TTS/n_best
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /exp/exp4/acq22mc/diff_list/Grad-TTS/n_best/config
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      hydra: sweep
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
seed: 1
'n': 10
n_best_list: /store/store4/data/nbests/tedlium/dev_tmp_out.pkl
diff_score_list: /exp/exp4/acq22mc/diff_list/logs/nbest_exp/e330_euler10_n10.csv
weights:
  first_pass_score: 0
  am_score: 0
  bpe_lm_score: 0
  first_pass_length_penalty: 0
  ngram_lm_score_non_oov: 0
  ngram_lm_score_oov: 0
  ngram_lm_score: 0
  second_pass_score: 0
  diffusion_score: 0
